// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RemoteCare.App.Persistencia;

namespace RemoteCare.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20220913173957_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("RemoteCare.App.Dominio.Historia_Clinica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ID_Dueño")
                        .HasColumnType("int");

                    b.Property<int>("ID_Oveja")
                        .HasColumnType("int");

                    b.Property<int>("ID_Veterinario")
                        .HasColumnType("int");

                    b.Property<int>("ID_Visita")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("HisClinic");
                });

            modelBuilder.Entity("RemoteCare.App.Dominio.Oveja", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dueño_Asignado")
                        .HasColumnType("int");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Raza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Veterinario_Asignado")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("oveja");
                });

            modelBuilder.Entity("RemoteCare.App.Dominio.Persona", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("RemoteCare.App.Dominio.Visita", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<float>("Frecuencia_Cardiaca")
                        .HasColumnType("real");

                    b.Property<float>("Frecuencia_Respiratoria")
                        .HasColumnType("real");

                    b.Property<int>("ID_Veterinario")
                        .HasColumnType("int");

                    b.Property<string>("Medicamentos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.Property<float>("Temperatura")
                        .HasColumnType("real");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("visita");
                });

            modelBuilder.Entity("RemoteCare.App.Dominio.Propietario", b =>
                {
                    b.HasBaseType("RemoteCare.App.Dominio.Persona");

                    b.Property<int>("Certificado")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Propietario");
                });

            modelBuilder.Entity("RemoteCare.App.Dominio.Veterinario", b =>
                {
                    b.HasBaseType("RemoteCare.App.Dominio.Persona");

                    b.Property<int>("Tarjeta_profesional")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Veterinario");
                });
#pragma warning restore 612, 618
        }
    }
}
